# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
        


from PyQt5 import QtCore, QtGui, QtWidgets
from helper import PlotCanvas

class Ui_MainWindow(object):
    
      
    def showWindowLoadCIFARData(self ):
        self.loadCIFARData.showMaximized()
        
        
    def showWindowTest(self ):
        self.test.showMaximized()
    
    def showWindowDisplayStatistics(self ):
        self.gridLayout_7.addWidget(self.sPlot)
        self.displayStatistics.showMaximized()
        
    def showWindowPreProcess(self ):
        self.preProcess.showMaximized()
        
    def showWindowCNNNetwork(self ):
        self.CNNNetwork.showMaximized()
        
    def showWindowClassify(self ):
        self.gridLayout_23.addWidget(self.cPlot)
        self.classify.showMaximized()

        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(40, 10, 910, 598))
        self.mdiArea.setObjectName("mdiArea")
        self.loadCIFARData = QtWidgets.QWidget()
        self.loadCIFARData.setObjectName("loadCIFARData")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.loadCIFARData)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.loadCIFARData)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(10)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.toolButtonCifarTest = QtWidgets.QToolButton(self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/LXI-294-VINU/.designer/backup/test.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonCifarTest.setIcon(icon)
        self.toolButtonCifarTest.setIconSize(QtCore.QSize(200, 200))
        self.toolButtonCifarTest.setObjectName("toolButtonCifarTest")
        self.gridLayout_6.addWidget(self.toolButtonCifarTest, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEditURL = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditURL.setObjectName("lineEditURL")
        self.horizontalLayout_3.addWidget(self.lineEditURL)
        self.pushButtonURL = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonURL.setFont(font)
        self.pushButtonURL.setObjectName("pushButtonURL")
        self.horizontalLayout_3.addWidget(self.pushButtonURL)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEditTar = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditTar.setObjectName("lineEditTar")
        self.horizontalLayout_2.addWidget(self.lineEditTar)
        self.pushButtonTar = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonTar.setFont(font)
        self.pushButtonTar.setObjectName("pushButtonTar")
        self.horizontalLayout_2.addWidget(self.pushButtonTar)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditFolder = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditFolder.setObjectName("lineEditFolder")
        self.horizontalLayout.addWidget(self.lineEditFolder)
        self.pushButtonFolder = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonFolder.setFont(font)
        self.pushButtonFolder.setObjectName("pushButtonFolder")
        self.horizontalLayout.addWidget(self.pushButtonFolder)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_5.addWidget(self.line_2, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.textBrowserInfo = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowserInfo.setObjectName("textBrowserInfo")
        self.gridLayout_4.addWidget(self.textBrowserInfo, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        self.test = QtWidgets.QWidget()
        self.test.setObjectName("test")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.test)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.groupBox_5 = QtWidgets.QGroupBox(self.test)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.buttonDataTests = QtWidgets.QPushButton(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonDataTests.setFont(font)
        self.buttonDataTests.setObjectName("buttonDataTests")
        self.horizontalLayout_16.addWidget(self.buttonDataTests)
        self.gridLayout_16.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_18.addWidget(self.label_8, 0, 0, 1, 1)
        self.buttonOneHotEncodeTests = QtWidgets.QPushButton(self.groupBox_4)
        self.buttonOneHotEncodeTests.setObjectName("buttonOneHotEncodeTests")
        self.gridLayout_18.addWidget(self.buttonOneHotEncodeTests, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_18.addWidget(self.label_9, 1, 0, 1, 1)
        self.buttonNormalisationTests = QtWidgets.QPushButton(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonNormalisationTests.setFont(font)
        self.buttonNormalisationTests.setObjectName("buttonNormalisationTests")
        self.gridLayout_18.addWidget(self.buttonNormalisationTests, 0, 1, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_4, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_10.addWidget(self.label_13, 0, 0, 1, 1)
        self.buttonImageInputTests = QtWidgets.QPushButton(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonImageInputTests.setFont(font)
        self.buttonImageInputTests.setObjectName("buttonImageInputTests")
        self.gridLayout_10.addWidget(self.buttonImageInputTests, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_10.addWidget(self.label_15, 2, 0, 1, 1)
        self.buttonKeepProbTests = QtWidgets.QPushButton(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonKeepProbTests.setFont(font)
        self.buttonKeepProbTests.setObjectName("buttonKeepProbTests")
        self.gridLayout_10.addWidget(self.buttonKeepProbTests, 3, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_10.addWidget(self.label_14, 4, 0, 1, 1)
        self.buttonLabelInputTests = QtWidgets.QPushButton(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonLabelInputTests.setFont(font)
        self.buttonLabelInputTests.setObjectName("buttonLabelInputTests")
        self.gridLayout_10.addWidget(self.buttonLabelInputTests, 5, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_11, 1, 0, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.groupBox_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.buttonFullyConvLayerTests = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonFullyConvLayerTests.setFont(font)
        self.buttonFullyConvLayerTests.setObjectName("buttonFullyConvLayerTests")
        self.gridLayout_21.addWidget(self.buttonFullyConvLayerTests, 1, 0, 1, 1)
        self.buttonCNNNetworkTests = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonCNNNetworkTests.setFont(font)
        self.buttonCNNNetworkTests.setObjectName("buttonCNNNetworkTests")
        self.gridLayout_21.addWidget(self.buttonCNNNetworkTests, 9, 0, 1, 1)
        self.buttonOutputLayerTests = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonOutputLayerTests.setFont(font)
        self.buttonOutputLayerTests.setObjectName("buttonOutputLayerTests")
        self.gridLayout_21.addWidget(self.buttonOutputLayerTests, 5, 0, 1, 1)
        self.buttonFlattenLayerTests = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonFlattenLayerTests.setFont(font)
        self.buttonFlattenLayerTests.setObjectName("buttonFlattenLayerTests")
        self.gridLayout_21.addWidget(self.buttonFlattenLayerTests, 7, 0, 1, 1)
        self.buttonConvMaxLayerTest = QtWidgets.QPushButton(self.groupBox_12)
        self.buttonConvMaxLayerTest.setObjectName("buttonConvMaxLayerTest")
        self.gridLayout_21.addWidget(self.buttonConvMaxLayerTest, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_21.addWidget(self.label_16, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_21.addWidget(self.label_18, 0, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_21.addWidget(self.label_20, 8, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_21.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_12)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_21.addWidget(self.label_19, 4, 0, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_12, 1, 1, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_5, 0, 0, 2, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.test)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_13)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_21 = QtWidgets.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_17.addWidget(self.label_21, 0, 0, 1, 1)
        self.buttonTrainingTests = QtWidgets.QPushButton(self.groupBox_13)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.buttonTrainingTests.setFont(font)
        self.buttonTrainingTests.setObjectName("buttonTrainingTests")
        self.gridLayout_17.addWidget(self.buttonTrainingTests, 0, 1, 1, 1)
        self.gridLayout_19.addWidget(self.groupBox_13, 0, 1, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.test)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_19.addWidget(self.textBrowser_2, 1, 1, 1, 1)
        self.displayStatistics = QtWidgets.QWidget()
        self.displayStatistics.setObjectName("displayStatistics")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.displayStatistics)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.displayStatistics)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_8.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 1, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.displayStatistics)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_15 = QtWidgets.QGroupBox(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_15)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBoxBatch = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBoxBatch.setObjectName("spinBoxBatch")
        self.gridLayout.addWidget(self.spinBoxBatch, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBoxSample = QtWidgets.QSpinBox(self.groupBox_15)
        self.spinBoxSample.setObjectName("spinBoxSample")
        self.spinBoxSample.setMaximum(100000)
        self.gridLayout.addWidget(self.spinBoxSample, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.buttonDisplayStatistics = QtWidgets.QToolButton(self.groupBox_15)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("statistics.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonDisplayStatistics.setIcon(icon1)
        self.buttonDisplayStatistics.setIconSize(QtCore.QSize(200, 200))
        self.buttonDisplayStatistics.setObjectName("buttonDisplayStatistics")
        self.gridLayout.addWidget(self.buttonDisplayStatistics, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_3, 0, 0, 1, 1)
        self.preProcess = QtWidgets.QWidget()
        self.preProcess.setObjectName("preProcess")
        self.label_10 = QtWidgets.QLabel(self.preProcess)
        self.label_10.setGeometry(QtCore.QRect(130, 160, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.buttonPreProcessAndSave = QtWidgets.QToolButton(self.preProcess)
        self.buttonPreProcessAndSave.setGeometry(QtCore.QRect(340, 140, 241, 81))
        self.buttonPreProcessAndSave.setObjectName("buttonPreProcessAndSave")
        self.CNNNetwork = QtWidgets.QWidget()
        self.CNNNetwork.setObjectName("CNNNetwork")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.CNNNetwork)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.groupBox_10 = QtWidgets.QGroupBox(self.CNNNetwork)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 0, 0, 1, 1)
        self.buttonShowStats = QtWidgets.QPushButton(self.groupBox_7)
        self.buttonShowStats.setObjectName("buttonShowStats")
        self.gridLayout_12.addWidget(self.buttonShowStats, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_25 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 0, 0, 2, 1)
        self.lineEditEpoch = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditEpoch.setObjectName("lineEditEpoch")
        self.gridLayout_11.addWidget(self.lineEditEpoch, 0, 1, 1, 1)
        self.lineEditBatchSize = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditBatchSize.setObjectName("lineEditBatchSize")
        self.gridLayout_11.addWidget(self.lineEditBatchSize, 1, 1, 2, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_11.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_11.addWidget(self.label_27, 3, 0, 1, 1)
        self.lineEditKeepProb = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEditKeepProb.setObjectName("lineEditKeepProb")
        self.gridLayout_11.addWidget(self.lineEditKeepProb, 3, 1, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_13.addWidget(self.label_24, 0, 0, 1, 1)
        self.buttonTrainOnSingleBatch = QtWidgets.QPushButton(self.groupBox_8)
        self.buttonTrainOnSingleBatch.setObjectName("buttonTrainOnSingleBatch")
        self.gridLayout_13.addWidget(self.buttonTrainOnSingleBatch, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_8, 2, 0, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_28 = QtWidgets.QLabel(self.groupBox_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_14.addWidget(self.label_28, 0, 0, 1, 1)
        self.buttonFullyTrainModel = QtWidgets.QPushButton(self.groupBox_9)
        self.buttonFullyTrainModel.setObjectName("buttonFullyTrainModel")
        self.gridLayout_14.addWidget(self.buttonFullyTrainModel, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_9, 3, 0, 1, 1)
        self.gridLayout_20.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.classify = QtWidgets.QWidget()
        self.classify.setObjectName("classify")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.classify)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.groupBox_14 = QtWidgets.QGroupBox(self.classify)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.label_2 = QtWidgets.QLabel(self.groupBox_14)
        self.label_2.setObjectName("label_2")
        self.gridLayout_22.addWidget(self.label_2, 0, 0, 1, 1)
        self.buttonRunClassificationOnTestData = QtWidgets.QPushButton(self.groupBox_14)
        self.buttonRunClassificationOnTestData.setObjectName("buttonRunClassificationOnTestData")
        self.gridLayout_22.addWidget(self.buttonRunClassificationOnTestData, 1, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_14, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuDisplay_Statistics = QtWidgets.QMenu(self.menubar)
        self.menuDisplay_Statistics.setObjectName("menuDisplay_Statistics")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuPreProcess = QtWidgets.QMenu(self.menubar)
        self.menuPreProcess.setObjectName("menuPreProcess")
        self.menuCNN_Network = QtWidgets.QMenu(self.menubar)
        self.menuCNN_Network.setObjectName("menuCNN_Network")
        self.menuClassify = QtWidgets.QMenu(self.menubar)
        self.menuClassify.setObjectName("menuClassify")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCIFAR_Data_Statistics = QtWidgets.QAction(MainWindow)
        self.actionCIFAR_Data_Statistics.setObjectName("actionCIFAR_Data_Statistics")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.actionLoad_CIFAR_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_CIFAR_Data.setObjectName("actionLoad_CIFAR_Data")
        self.actionTest = QtWidgets.QAction(MainWindow)
        self.actionTest.setObjectName("actionTest")
        self.actionPreProcess = QtWidgets.QAction(MainWindow)
        self.actionPreProcess.setObjectName("actionPreProcess")
        self.actionClassify = QtWidgets.QAction(MainWindow)
        self.actionClassify.setObjectName("actionClassify")
        self.actionCNN_Network = QtWidgets.QAction(MainWindow)
        self.actionCNN_Network.setObjectName("actionCNN_Network")
        self.menuFile.addAction(self.actionLoad_CIFAR_Data)
        self.menuDisplay_Statistics.addAction(self.actionCIFAR_Data_Statistics)
        self.menuTest.addAction(self.actionTest)
        self.menuPreProcess.addAction(self.actionPreProcess)
        self.menuCNN_Network.addAction(self.actionCNN_Network)
        self.menuClassify.addAction(self.actionClassify)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDisplay_Statistics.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuPreProcess.menuAction())
        self.menubar.addAction(self.menuCNN_Network.menuAction())
        self.menubar.addAction(self.menuClassify.menuAction())

        self.retranslateUi(MainWindow)
        
        
        self.cPlot = PlotCanvas(self.classify, width=5, height=4)
        self.cPlot.move(0,0)
        
        self.sPlot = PlotCanvas(self.displayStatistics, width=5, height=4)
        self.sPlot.move(0,0)
        
        
        
        
#         Link Sub Windows to the MDI
        self.mdiArea.addSubWindow(self.loadCIFARData)
        self.mdiArea.addSubWindow(self.test)
        self.mdiArea.addSubWindow(self.displayStatistics)
        self.mdiArea.addSubWindow(self.preProcess)
        self.mdiArea.addSubWindow(self.CNNNetwork)
        self.mdiArea.addSubWindow(self.classify)
        
        self.loadCIFARData.showMaximized()
        
#        Link Sub Windows and the  Menu
        
        self.menuFile.triggered.connect(self.showWindowLoadCIFARData)
        self.menuTest.triggered.connect(self.showWindowTest)
        self.menuDisplay_Statistics.triggered.connect(self.showWindowDisplayStatistics)
        self.menuPreProcess.triggered.connect(self.showWindowPreProcess)
        self.menuCNN_Network.triggered.connect(self.showWindowCNNNetwork)
        self.menuClassify.triggered.connect(self.showWindowClassify)
        
#        Connect the slots to the buttons and lineEdits
        
        self.pushButtonFolder.clicked.connect( self.browseFolderSlot)
        self.pushButtonTar.clicked.connect( self.browseTarSlot)
        self.pushButtonURL.clicked.connect( self.returnPressedURLSlot)
        
        self.lineEditFolder.returnPressed.connect( self.returnPressedFolderSlot)
        self.lineEditTar.returnPressed.connect( self.returnPressedTarSlot)
        self.lineEditURL.returnPressed.connect( self.returnPressedURLSlot)
        
        self.buttonRunClassificationOnTestData.clicked.connect(self.runClassificationOnTestData)
        
        
        
        self.toolButtonCifarTest.clicked.connect(self.runCifarTest)
        self.buttonDataTests.clicked.connect(self.runDataTests)
        self.buttonImageInputTests.clicked.connect(self.runImageInputTests)
        self.buttonKeepProbTests.clicked.connect(self.runKeepProbTests)
        self.buttonLabelInputTests.clicked.connect(self.runLabelInputTests)
        self.buttonNormalisationTests.clicked.connect(self.runNormalisationTests)
        self.buttonOneHotEncodeTests.clicked.connect(self.runOneHotEncodeTests)
        self.buttonFullyConvLayerTests.clicked.connect(self.runFullyConvLayerTests)
        self.buttonConvMaxLayerTest.clicked.connect(self.runConvMaxLayerTest)
        self.buttonOutputLayerTests.clicked.connect(self.runOutputLayerTests)
        self.buttonFlattenLayerTests.clicked.connect(self.runFlattenLayerTests)
        self.buttonCNNNetworkTests.clicked.connect(self.runCNNNetworkTests)
        self.buttonTrainingTests.clicked.connect(self.runTrainingTests)
        self.buttonDisplayStatistics.clicked.connect(self.runDisplayStatistics)
        self.buttonPreProcessAndSave.clicked.connect(self.runPreProcessAndSave)
        self.buttonShowStats.clicked.connect(self.runShowStats)
        self.buttonTrainOnSingleBatch.clicked.connect(self.runTrainOnSingleBatch)
        self.buttonFullyTrainModel.clicked.connect(self.runFullyTrainModel)
       
        
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadCIFARData.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Test CIFAR Data"))
        self.toolButtonCifarTest.setText(_translate("MainWindow", "Test"))
        self.groupBox.setTitle(_translate("MainWindow", "Load CIFAR Data"))
        self.label_5.setText(_translate("MainWindow", "DataSet URL"))
        self.pushButtonURL.setText(_translate("MainWindow", "Download"))
        self.label_4.setText(_translate("MainWindow", "DataSet Tar"))
        self.pushButtonTar.setText(_translate("MainWindow", "Unzip"))
        self.label.setText(_translate("MainWindow", "DataSet Folder"))
        self.pushButtonFolder.setText(_translate("MainWindow", "Browse"))
        self.test.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "CNN Network"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Data Tests"))
        self.label_7.setText(_translate("MainWindow", "Data and Test Files"))
        self.buttonDataTests.setText(_translate("MainWindow", "Data Tests"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Pre Process Tests"))
        self.label_8.setText(_translate("MainWindow", "Test Normalize"))
        self.buttonOneHotEncodeTests.setText(_translate("MainWindow", "One Hot Encode Test"))
        self.label_9.setText(_translate("MainWindow", "Test One Hot Encode"))
        self.buttonNormalisationTests.setText(_translate("MainWindow", "Normalisation Test"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Input Tests"))
        self.label_13.setText(_translate("MainWindow", "Image Inputs"))
        self.buttonImageInputTests.setText(_translate("MainWindow", "Image Input Test"))
        self.label_15.setText(_translate("MainWindow", "Probability Inputs"))
        self.buttonKeepProbTests.setText(_translate("MainWindow", "Keep Prob Test"))
        self.label_14.setText(_translate("MainWindow", "Label Inputs"))
        self.buttonLabelInputTests.setText(_translate("MainWindow", "Label Inputs Test"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Layer Tests"))
        self.buttonFullyConvLayerTests.setText(_translate("MainWindow", "Fully Connected Layer Test"))
        self.buttonCNNNetworkTests.setText(_translate("MainWindow", "CNN Network Test"))
        self.buttonOutputLayerTests.setText(_translate("MainWindow", "Output Layer Test"))
        self.buttonFlattenLayerTests.setText(_translate("MainWindow", "Flatten Layer Test"))
        self.buttonConvMaxLayerTest.setText(_translate("MainWindow", "Convolution and Max Pool Layer Test"))
        self.label_16.setText(_translate("MainWindow", "Convolution and Max Pool Layer"))
        self.label_18.setText(_translate("MainWindow", "Fully Connected Layer"))
        self.label_20.setText(_translate("MainWindow", "CNN Network"))
        self.label_17.setText(_translate("MainWindow", "Flatten Layer"))
        self.label_19.setText(_translate("MainWindow", "Output Layer"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Training Tests"))
        self.label_21.setText(_translate("MainWindow", "Training"))
        self.buttonTrainingTests.setText(_translate("MainWindow", "Training Tests"))
        self.displayStatistics.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Display Statistics"))
        self.label_6.setText(_translate("MainWindow", "Sample ID"))
        self.label_3.setText(_translate("MainWindow", "Batch ID"))
        self.buttonDisplayStatistics.setText(_translate("MainWindow", "Display Statistics"))
        self.label_11.setText(_translate("MainWindow", "Stats of batch :\n"
"Samples: \n"
"Label Counts: \n"
"First 20 Labels: \n"
"Example of Image:\n"
"Image - Min Value: Max Value: \n"
"Image - Shape: \n"
"Label - Label Id: \n"
"Name: "))
        self.preProcess.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_10.setText(_translate("MainWindow", "PreProcess"))
        self.buttonPreProcessAndSave.setText(_translate("MainWindow", "PreProcess and Save Data"))
        self.CNNNetwork.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.groupBox_10.setTitle(_translate("MainWindow", "CNN"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Show Stats"))
        self.label_23.setText(_translate("MainWindow", "Show Stats"))
        self.buttonShowStats.setText(_translate("MainWindow", "Show Stats"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Tune Parameters"))
        self.label_25.setText(_translate("MainWindow", "Epoch"))
        self.label_26.setText(_translate("MainWindow", "Batch Size"))
        self.label_27.setText(_translate("MainWindow", "Keep Probability"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Train on Single Batch"))
        self.label_24.setText(_translate("MainWindow", "Train on Single Batch"))
        self.buttonTrainOnSingleBatch.setText(_translate("MainWindow", "Train on Single Batch"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Fully Train Model"))
        self.label_28.setText(_translate("MainWindow", "Fully Train Model"))
        self.buttonFullyTrainModel.setText(_translate("MainWindow", "Fully Train Model"))
        self.classify.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Classify"))
        self.label_2.setText(_translate("MainWindow", "Run Classification on Test Data"))
        self.buttonRunClassificationOnTestData.setText(_translate("MainWindow", "Run Classification on Test Data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuDisplay_Statistics.setTitle(_translate("MainWindow", "Display Statistics"))
        self.menuTest.setTitle(_translate("MainWindow", "Test"))
        self.menuPreProcess.setTitle(_translate("MainWindow", "PreProcess"))
        self.menuCNN_Network.setTitle(_translate("MainWindow", "CNN Network"))
        self.menuClassify.setTitle(_translate("MainWindow", "Classify"))
        self.actionCIFAR_Data_Statistics.setText(_translate("MainWindow", "CIFAR Data Statistics"))
        self.action1.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.actionLoad_CIFAR_Data.setText(_translate("MainWindow", "Load CIFAR Data"))
        self.actionTest.setText(_translate("MainWindow", "Test"))
        self.actionPreProcess.setText(_translate("MainWindow", "PreProcess"))
        self.actionClassify.setText(_translate("MainWindow", "Classify"))
        self.actionCNN_Network.setText(_translate("MainWindow", "CNN Network"))

